=head1 NAME

makebeamerinfo - Creates .info file for use with Impressive and LaTeX Beamer

=head1 DOCUMENTATION

Users looking for usage information should look at L<makebeamerinfo>. For subclassing information (not stable yet) one might look at L<App::makebeamerinfo>.

=head1 INSTALLATION

Information coming soon.

=head1 SEE ALSO

=over 4

=item *

L<Impressive|http://impressive.sourceforge.net/>

=item *

L<LaTeX Beamer|http://latex-beamer.sourceforge.net/>

=back

=head1 SOURCE REPOSITORY

L<http://github.com/jberger/MakeBeamerInfo>

=head1 AUTHOR

Joel Berger, E<lt>joel.a.berger@gmail.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2012 by Joel Berger

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

